config/routes.rb
Rails.application.routes.draw do

  
  get 'contacts/new'

  get 'contacts/create'

  resources :promotions
  resources :equipment
  resources :slides
  resources :workers
  
  get 'admin/connect'
  post 'admin/connect'
  get 'admin/logout'

  get 'attachment/show/:id', to: 'attachment#show', as: 'attachment_show'

  resources :equip_people

  get 'home', to: 'information#show', defaults:{name: 'home'}
  get 'charter', to: 'information#show', defaults:{name: 'charter'}
  get 'schedule', to: 'information#show', defaults:{name: 'schedule'}
  get 'map', to: 'information#show', defaults:{name: 'map'}

  get 'home/edit', to: 'information#edit', defaults:{name: 'home'}
  get 'charter/edit', to: 'information#edit', defaults:{name: 'charter'}
  get 'schedule/edit', to: 'information#edit', defaults:{name: 'schedule'}
  get 'map/edit', to: 'information#edit', defaults:{name: 'map'}

  patch 'information/:id', to: 'information#update', as: 'information'


  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	def uploaded_file=(incoming_file)
		self.filename = incoming_file.original_filename
		self.content_type = incoming_file.content_type
		self.data = incoming_file.read
	end

	def filename=(new_filename)
		write_attribute("filename", sanitize_filename(new_filename))
	end

	private
		def sanitize_filename(filename)
			just_filename = File.basename(filename)
			just_filename.gsub(/[^\w\.\-]/, '_')
		end
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, :validate => true
	attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message
	attribute :nickname, :captcha => true

	def headers
		{
			:subject => "My Contact Form",
			:to => "amettixo-8701@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/equip_person.rb
class EquipPerson < ApplicationRecord
end

app/models/equipment.rb
class Equipment < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def connect
    @title = "Connexion réservée à l'administrateur"
  	return if params[:password].blank?
  	return if params[:password] != "mdp35pharma\#"
  	session[:admin] = true
  	redirect_to :home, notice: 'Connexion en tant qu\'administrateur réussie.'
  end

  def logout
    admin_only
  	session[:password] = false
  	session[:admin] = false
  	redirect_to :home, notice: "Déconnexion réussie."
  end
end

def admin?
  !session[:admin].blank? && session[:admin] == true
end

def admin_only
  if !admin?
    redirect_to :home, notice: "Opération interdite"
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @title = "Visite guidée"
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    admin_only
    @title = "Ajouter une diapositive"
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
    admin_only
    @tite = "Modifier une diapositive"
  end

  # POST /slides
  # POST /slides.json
  def create
    admin_only
    return if params[:attachment].blank?

    @attachment = Attachment.new
    @attachment.uploaded_file = params[:attachment]

    @slide = Slide.new
    @slide.description = params[:description]

    if @attachment.save
      @slide.id_attachment = @attachment.id
      if @slide.save
        redirect_to "/slides", notice: 'La diapositive a bien été ajoutée.'
      else
        attachment.delete
        render :new
      end
    else
      render :new
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    admin_only
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'La diapositive a bien été modifiée.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    admin_only
    Attachment.find(@slide.id_attachment).destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'La diapositive a bien été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:id_attachment, :description)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @title = "Professionnels de la santé"
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    admin_only
    @title = "Ajout d'un professionnel de la santé"
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
    admin_only
  end

  # POST /workers
  # POST /workers.json
  def create
    admin_only
    @worker = Worker.new(worker_params)

=begin
    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
=end

    if @worker.save
      redirect_to action: "index", notice: "Le professionnel de la santé a bien été ajouté."
    else
      render :new
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    admin_only
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Le professionnel de la santé a bien été modifié.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    admin_only
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Le professionnel de la santé a bien été retiré.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :description, :address, :tel)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachment_helper.rb
module AttachmentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equip_people_helper.rb
module EquipPeopleHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/slides/_form.html.erb
<%= form_tag({:action => 'index'}, :multipart => true) do %>
  <% if slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag(:description, "Description :") %>
    <%= text_area_tag(:description) %>
  </div>
  
  <div class="field">
    <%= label_tag(:attachment, "Image :") %>
    <%= file_field_tag(:attachment) %>
  </div>
  
  <div class="actions">
    <%= submit_tag "Valider" %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<%= render 'form', slide: @slide %>

<%= link_to 'Afficher', @slide %> |
<%= link_to 'Retour', slides_path %>

app/views/slides/index.html.erb
<h1>Visite guidée</h1>

<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <% if Slide.count > 0 %>
    <ol class="carousel-indicators">
      <% for i in 0..Slide.count-1 do %>
        <li data-target="#myCarousel" data-slide-to="<%= i %>"<%= ' class="active"' if i==0 %>></li>
      <% end %>
    </ol>
  <% end %>

  <div class="carousel-inner" role="listbox">
    <% isFirst = true %>
    <% @slides.each do |slide| %>
      <div class="item<%= ' active' if isFirst %>">
        <%= image_tag attachment_show_path(slide.id_attachment) %>
        <div class="carousel-caption">
          <p><%= slide.description %></p>
          <%= render partial: "shared/edit_link", locals: {path: edit_slide_path(slide)} %>
          <%= render partial: "shared/remove_link", locals: {object: slide} %>
          <% isFirst = false %>
        </div>
      </div>
    <% end %>
  </div>

  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Précédent</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Suivant</span>
  </a>
</div>
<br>

<%= render partial: "shared/add_link", locals: {path: new_slide_path, text: "Ajouter une diapositive"} %>

app/views/slides/new.html.erb
<%= render 'form', slide: @slide %>

<%= link_to 'Retour', slides_path %>

app/views/slides/show.html.erb
<p>
  <strong>Id attachment:</strong>
  <%= @slide.id_attachment %>
</p>

<p>
  <strong>Description:</strong>
  <%= @slide.description %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>

app/views/workers/_form.html.erb
<%= form_for(worker) do |f| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nom :" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :address, "Adresse :" %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :tel, "Tél :" %>
    <%= f.text_field :tel %>
  </div>

  <div class="actions">
    <%= f.submit "Ajouter" %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<% @workers.each do |worker| %>
  <div class="person well">
    <div class="name"><%= worker.name %></div>
    <div class="description">
      <%= worker.description %><br/>
      Adresse : <%= worker.address %><br/>
      Tél : <%= worker.tel %><br/>
      <%= render partial: "shared/edit_link", locals: {path: edit_worker_path(worker)} %>
      <%= render partial: "shared/remove_link", locals: {object: worker} %>
    </div>
    </div>
<% end %>

<br/>

<%= render partial: "shared/add_link", locals: {path: new_worker_path, text: "Ajouter un professionnel de la santé"} %>

app/views/workers/new.html.erb
<h1>Nouveau professionnel de la santé</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Retour', workers_path %>

app/views/workers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @worker.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @worker.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @worker.tel %>
</p>

<%= link_to 'Modifier', edit_worker_path(@worker) %> |
<%= link_to 'Retour', workers_path %>