config/routes.rb
Rails.application.routes.draw do

  
  get 'contacts/new'

  get 'contacts/create'

  resources :promotions
  resources :equipment
  resources :slides
  resources :workers
  
  get 'admin/connect'
  post 'admin/connect'
  get 'admin/logout'

  get 'attachment/show/:id', to: 'attachment#show', as: 'attachment_show'

  resources :equip_people

  get 'home', to: 'information#show', defaults:{name: 'home'}
  get 'charter', to: 'information#show', defaults:{name: 'charter'}
  get 'schedule', to: 'information#show', defaults:{name: 'schedule'}
  get 'map', to: 'information#show', defaults:{name: 'map'}

  get 'home/edit', to: 'information#edit', defaults:{name: 'home'}
  get 'charter/edit', to: 'information#edit', defaults:{name: 'charter'}
  get 'schedule/edit', to: 'information#edit', defaults:{name: 'schedule'}
  get 'map/edit', to: 'information#edit', defaults:{name: 'map'}

  patch 'information/:id', to: 'information#update', as: 'information'


  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	def uploaded_file=(incoming_file)
		self.filename = incoming_file.original_filename
		self.content_type = incoming_file.content_type
		self.data = incoming_file.read
	end

	def filename=(new_filename)
		write_attribute("filename", sanitize_filename(new_filename))
	end

	private
		def sanitize_filename(filename)
			just_filename = File.basename(filename)
			just_filename.gsub(/[^\w\.\-]/, '_')
		end
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, :validate => true
	attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message
	attribute :nickname, :captcha => true

	def headers
		{
			:subject => "My Contact Form",
			:to => "amettixo-8701@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/equip_person.rb
class EquipPerson < ApplicationRecord
end

app/models/equipment.rb
class Equipment < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def connect
    @title = "Connexion réservée à l'administrateur"
  	return if params[:password].blank?
  	return if params[:password] != "mdp35pharma\#"
  	session[:admin] = true
  	redirect_to :home, notice: 'Connexion en tant qu\'administrateur réussie.'
  end

  def logout
    admin_only
  	session[:password] = false
  	session[:admin] = false
  	redirect_to :home, notice: "Déconnexion réussie."
  end
end

def admin?
  !session[:admin].blank? && session[:admin] == true
end

def admin_only
  if !admin?
    redirect_to :home, notice: "Opération interdite"
  end
end

app/controllers/equip_people_controller.rb
class EquipPeopleController < ApplicationController
  before_action :set_equip_person, only: [:show, :edit, :update, :destroy]

  # GET /equip_people
  # GET /equip_people.json
  def index
    @title = "L'équipe"
    @equip_people = EquipPerson.all
  end

  # GET /equip_people/1
  # GET /equip_people/1.json
  def show
  end

  # GET /equip_people/new
  def new
    admin_only
    @title = "Ajout d'un membre de l'équipe"
    @equip_person = EquipPerson.new
  end

  # GET /equip_people/1/edit
  def edit
    admin_only
    @title = "Modifier un membre de l'équipe"
  end

  # POST /equip_people
  # POST /equip_people.json
  def create
    admin_only
    return if params[:attachment].blank?

    @attachment = Attachment.new
    @attachment.uploaded_file = params[:attachment]

    @equip_person = EquipPerson.new
    @equip_person.name = params[:name]
    @equip_person.description = params[:description]

    respond_to do |format|
      if @attachment.save
        @equip_person.id_attachment = @attachment.id
        if @equip_person.save
          #format.html { redirect_to @equip_person, notice: 'Equip person was successfully created.' }
          #format.json { render :show, status: :created, location: @equip_person }
          format.html { redirect_to "equip_people", notice: "Le membre de l'équipe a bien été ajouté." }
          format.json { render "equip_people", status: :created }
        else
          @attachment.delete
          format.html { render :new }
          format.json { render json: @equip_person.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @equip_person.errors, status: :unprocessable_entity }
      end
    end
=begin
    respond_to do |format|
      if @equip_person.save
        format.html { redirect_to @equip_person, notice: 'Equip person was successfully created.' }
        format.json { render :show, status: :created, location: @equip_person }
      else
        format.html { render :new }
        format.json { render json: @equip_person.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /equip_people/1
  # PATCH/PUT /equip_people/1.json
  def update
    admin_only
    respond_to do |format|
      if @equip_person.update(equip_person_params)
        format.html { redirect_to @equip_person, notice: 'Le membre de l\'équipe a bien été modifié.' }
        format.json { render :show, status: :ok, location: @equip_person }
      else
        format.html { render :edit }
        format.json { render json: @equip_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equip_people/1
  # DELETE /equip_people/1.json
  def destroy
    Attachment.find(@equip_person.id_attachment).destroy
    @equip_person.destroy
    respond_to do |format|
      format.html { redirect_to equip_people_url, notice: 'Le membre de l\'équipe a bien été retiré.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equip_person
      @equip_person = EquipPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equip_person_params
      params.require(:equip_person).permit(:name, :id_attachment, :description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachment_helper.rb
module AttachmentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equip_people_helper.rb
module EquipPeopleHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/equip_people/_form.html.erb
<%= form_tag({:action => 'index'}, :multipart => true) do %>
<%#= form_for(equip_person) do |f| %>
  <% if equip_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equip_person.errors.count, "error") %> prohibited this equip_person from being saved:</h2>

      <ul>
      <% equip_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag(:name, "Name:") %>
    <%= text_field_tag(:name) %>
  </div>

  <div class="field">
    <%= label_tag(:description, "Description:") %>
    <%= text_area_tag(:description) %>
  </div>
  
  <div class="field">
    <%= label_tag(:attachment, "Image:") %>
    <%= file_field_tag(:attachment) %>
  </div>
  
  <div class="actions">
    <%= submit_tag "Valider" %>
  </div>
<% end %>

app/views/equip_people/edit.html.erb
<%= render 'form', equip_person: @equip_person %>

<%= link_to 'Afficher', @equip_person %> |
<%= link_to 'Retour', equip_people_path %>

app/views/equip_people/index.html.erb
<!--<div class="container">
<div class="row">-->
<% @equip_people.each do |equip_person| %>
  <div class="person well">
  <!--<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">-->
    <div class="name"><%= equip_person.name %></div>
    <div class="photo"><%= image_tag attachment_show_path(equip_person.id_attachment) %></div>
    <div class="description">
      <%= equip_person.description %><br/>
      <%= render partial: "shared/edit_link", locals: {path: edit_equip_person_path(equip_person)} %>
      <%= render partial: "shared/remove_link", locals: {object: equip_person} %>
    </div>
  </div>
<% end %>

<br/>

<%= render partial: "shared/add_link", locals: {path: new_equip_person_path, text: "Ajouter un membre de l'équipe"} %>

app/views/equip_people/new.html.erb
<%= render 'form', equip_person: @equip_person %>

<%= link_to 'Retour', equip_people_path %>

app/views/equip_people/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @equip_person.name %>
</p>

<p>
  <strong>Id attachment:</strong>
  <%= @equip_person.id_attachment %>
</p>

<p>
  <strong>Description:</strong>
  <%= @equip_person.description %>
</p>

<%= link_to 'Modifier', edit_equip_person_path(@equip_person) %> |
<%= link_to 'Retour', equip_people_path %>